/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client"
import { Gltf } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

const modelUrl = "https://pub-897cab9d4e9f455983feccce16991279.r2.dev/clan-one-virtual-room.glb";

export default function Model(props: any) {

  return (
    <>
      <group>
        <RigidBody type="fixed" colliders="trimesh">
          <Gltf src={modelUrl} scale={1} position={[0, 2, 0]} {...props} />
        </RigidBody>
      </group>
    </>

  )
}
