/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client"
import React, { useRef } from 'react'
import { Gltf, useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props: any) {
  return (
    <Gltf src="https://pub-897cab9d4e9f455983feccce16991279.r2.dev/clan-one-room-v6-1.glb" scale={1} position={[0, 0, 0]} {...props} />
  )
}
