/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Gltf, useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props: any) {
  return (
    <Gltf src="/models/room.glb" scale={1} position={[0, 0, 0]} {...props} />
  )
}

useGLTF.preload('/Poimandres.gltf')